package Clases;
// Generated 07-mar-2020 14:35:09 by Hibernate Tools 4.3.1



/**
 * Pais generated by hbm2java
 */
public class Pais  implements java.io.Serializable {


     private Integer idPais;
     private String nombre;
     private String zonaHoraria;
     private String continente;

    public Pais() {
    }

    public Pais(String nombre, String zonaHoraria, String continente) {
       this.nombre = nombre;
       this.zonaHoraria = zonaHoraria;
       this.continente = continente;
    }
   
    public Integer getIdPais() {
        return this.idPais;
    }
    
    public void setIdPais(Integer idPais) {
        this.idPais = idPais;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getZonaHoraria() {
        return this.zonaHoraria;
    }
    
    public void setZonaHoraria(String zonaHoraria) {
        this.zonaHoraria = zonaHoraria;
    }
    public String getContinente() {
        return this.continente;
    }
    
    public void setContinente(String continente) {
        this.continente = continente;
    }




}


